version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
    - ../kma_ndt_kyso/build:/var/www/kmakyso/html
    - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
  backend:
    build:
      context: ../kma_ndt_serve
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
